# using default_language_version
default_language_version:
    node: 16.14.2

repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: trailing-whitespace
      exclude: ^tests/resources/
    - id: end-of-file-fixer
      exclude: ^tests/resources/
    - id: check-yaml
      args: ["--unsafe"]
    - id: check-ast
    - id: check-json
    - id: debug-statements
    - id: detect-aws-credentials
      args: [--allow-missing-credentials]
    - id: detect-private-key
    - id: check-merge-conflict
    - id: check-added-large-files
      args: ['--maxkb=3000']

-   repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    - id: black
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
        args: ["--ignore-missing-imports", "--explicit-package-bases"]
