name: syn-retro
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pillow
  - psycopg2
  - pydantic
  - rdkit
  - tqdm
  - scikit-learn
  - umap-learn
  - sqlalchemy
  - pytest
  - chemicalite
